max_width = 100
newline_style = "Native"
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true

# Nightly Only
fn_single_line = false
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Crate"
trailing_comma = "Never"
unstable_features = true
