[package]
name = "server-fns-core"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
syn = { workspace = true, features = [
    "parsing",
    "derive",
    "full",
    "extra-traits",
    "printing",
] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
inventory = { workspace = true }
axum = { workspace = true }
deluxe = { workspace = true }
derive-syn-parse = { workspace = true }
itertools = { workspace = true }
convert_case = { workspace = true }
static_assertions = { workspace = true }

[dev-dependencies]
seq-macro = { workspace = true }
