[package]
name = "server-fns-procm"

edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
paste           = { workspace = true }
server-fns-core = { workspace = true }
