[package]
name = "server-fns-procm"
version = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
server-fns-core = { workspace = true }
paste = { workspace = true }
