[package]
name = "server-state"
version.workspace = true
edition.workspace = true

[features]
default = ["server"]
web = ["server-fns/web"]
server = ["server-fns/server"]

[dependencies]
axum = { workspace = true }
server-fns = { workspace = true }
